# ---------- PALETAS DE COLORES (MEJORADAS) ----------
color_schemes = {
    "Mono Dark": {  # SIN CAMBIOS
        "bg_main": "#0D0D0D",
        "bg_secondary": "#232323",
        "bg_card": "#343434",
        "text_primary": "#E8E8E8",
        "text_secondary": "#B0B0B0",
        "accent": "#D4AF37",
        "accent_hover": "#B8952A",
        "select_bg": "#464646",
        "select_fg": "#FFFFFF",
        "button_scan": "#7A7A7A",
        "button_scan_hover": "#595959",
        "button_play": "#D4AF37",
        "button_play_hover": "#B8952A",
        "button_stop": "#FF5E5B",
        "button_stop_hover": "#E65150",
        "button_nav": "#464646",
        "button_nav_hover": "#575757",
        "button_metro": "#575757",
        "button_metro_hover": "#696969",
        "button_metro_on": "#D4AF37",
        "button_text": "#FFFFFF",
        "pulse_color": "#D4AF37",
        "pulse_color_hover": "#B8952A",
    },

    "Bright Pop": {
        "bg_main": "#FFFDF5",
        "bg_secondary": "#222222",
        "bg_card": "#FFFFFF",
        "text_primary": "#1C1C1C",
        "text_secondary": "#3A3A3A",
        "accent": "#00B8B5",
        "accent_hover": "#009E9C",
        "select_bg": "#00CECB",
        "select_fg": "#FFFFFF",
        "button_scan": "#FF6F61",
        "button_scan_hover": "#E65B4F",
        "button_play": "#FFE75A",
        "button_play_hover": "#E6D351",
        "button_stop": "#FF6F61",
        "button_stop_hover": "#E65B4F",
        "button_nav": "#00B8B5",
        "button_nav_hover": "#009E9C",
        "button_metro": "#FFE75A",
        "button_metro_hover": "#E6D351",
        "button_metro_on": "#00B8B5",
        "button_text": "#1C1C1C",
        "pulse_color": "#00B8B5",
        "pulse_color_hover": "#009E9C",
    },

    "Stage Night": {
        "bg_main": "#0C0C0C",
        "bg_secondary": "#1A1A1A",
        "bg_card": "#232323",
        "text_primary": "#F0EAD6",
        "text_secondary": "#C6BFAE",
        "accent": "#D4AF37",
        "accent_hover": "#B8952A",
        "select_bg": "#D4AF37",
        "select_fg": "#0C0C0C",
        "button_scan": "#FF6F61",
        "button_scan_hover": "#E65B4F",
        "button_play": "#00E676",
        "button_play_hover": "#00C46B",
        "button_stop": "#FF3B5F",
        "button_stop_hover": "#E03054",
        "button_nav": "#D4AF37",
        "button_nav_hover": "#B8952A",
        "button_metro": "#3A86FF",
        "button_metro_hover": "#296DDB",
        "button_metro_on": "#00E676",
        "button_text": "#000000",
        "pulse_color": "#FFD700",
        "pulse_color_hover": "#D4AF37",
    },

    "Ocean Light": {
        "bg_main": "#F4FBFF",
        "bg_secondary": "#01497C",
        "bg_card": "#E7F3F9",
        "text_primary": "#012A4A",
        "text_secondary": "#27638D",
        "accent": "#0275A8",
        "accent_hover": "#015F87",
        "select_bg": "#2C7DA0",
        "select_fg": "#FFFFFF",
        "button_scan": "#5EA7C8",
        "button_scan_hover": "#4D91B1",
        "button_play": "#80C4E0",
        "button_play_hover": "#5EA7C8",
        "button_stop": "#01497C",
        "button_stop_hover": "#013A63",
        "button_nav": "#2A6F97",
        "button_nav_hover": "#015F87",
        "button_metro": "#80C4E0",
        "button_metro_hover": "#5EA7C8",
        "button_metro_on": "#01497C",
        "button_text": "#FFFFFF",
        "pulse_color": "#0275A8",
        "pulse_color_hover": "#015F87",
    },

    "Forest Calm": {
        "bg_main": "#F6FBF8",
        "bg_secondary": "#14746F",
        "bg_card": "#E5F5ED",
        "text_primary": "#124E4A",
        "text_secondary": "#3D857D",
        "accent": "#1E8277",
        "accent_hover": "#166B63",
        "select_bg": "#4FAE9B",
        "select_fg": "#FFFFFF",
        "button_scan": "#99E2B4",
        "button_scan_hover": "#78C6A3",
        "button_play": "#4FAE9B",
        "button_play_hover": "#3E9D89",
        "button_stop": "#036666",
        "button_stop_hover": "#0F5A59",
        "button_nav": "#1E8277",
        "button_nav_hover": "#166B63",
        "button_metro": "#78C6A3",
        "button_metro_hover": "#56AB91",
        "button_metro_on": "#036666",
        "button_text": "#FFFFFF",
        "pulse_color": "#4FAE9B",
        "pulse_color_hover": "#3E9D89",
    },

    "Abyss Dark": {  # SIN CAMBIOS
        "bg_main": "#000E14",
        "bg_secondary": "#00141F",
        "bg_card": "#001B29",
        "text_primary": "#D9E2EC",
        "text_secondary": "#9FB3C8",
        "accent": "#003652",
        "accent_hover": "#003D5C",
        "select_bg": "#00293D",
        "select_fg": "#FFFFFF",
        "button_scan": "#003047",
        "button_scan_hover": "#003652",
        "button_play": "#00C48E",
        "button_play_hover": "#00AA7A",
        "button_stop": "#FF3366",
        "button_stop_hover": "#E02E5B",
        "button_nav": "#005C99",
        "button_nav_hover": "#004A7D",
        "button_metro": "#0074D9",
        "button_metro_hover": "#0061B5",
        "button_metro_on": "#00E676",
        "button_text": "#000000",
        "pulse_color": "#00C48E",
        "pulse_color_hover": "#00AA7A",
    },

    "Midnight Core 2": {
        "bg_main": "#14746F",
        "bg_secondary": "#036666",
        "bg_card": "#1D7A72",
        "text_primary": "#FFFFFF",
        "text_secondary": "#DCEEE6",
        "accent": "#56AB91",
        "accent_hover": "#67B99A",
        "select_bg": "#88D4AB",
        "select_fg": "#013A36",
        "button_scan": "#99E2B4",
        "button_scan_hover": "#88D4AB",
        "button_play": "#55A630",
        "button_play_hover": "#80B918",
        "button_stop": "#AACC00",
        "button_stop_hover": "#D4D700",
        "button_nav": "#469D89",
        "button_nav_hover": "#358F80",
        "button_metro": "#248277",
        "button_metro_hover": "#14746F",
        "button_metro_on": "#55A630",
        "button_text": "#0D0D0D",
        "pulse_color": "#56AB91",
        "pulse_color_hover": "#67B99A",
    },

    "Forest Depth": {
        "bg_main": "#0E1B24",
        "bg_secondary": "#14252F",
        "bg_card": "#1C3038",
        "text_primary": "#E9E9E9",
        "text_secondary": "#A7B3B0",
        "accent": "#2F5454",
        "accent_hover": "#396262",
        "select_bg": "#305252",
        "select_fg": "#FFFFFF",
        "button_scan": "#3A4B4E",
        "button_scan_hover": "#344647",
        "button_play": "#3C4547",
        "button_play_hover": "#374041",
        "button_stop": "#2E3B3E",
        "button_stop_hover": "#253033",
        "button_nav": "#345D5C",
        "button_nav_hover": "#2F5454",
        "button_metro": "#396262",
        "button_metro_hover": "#2F5454",
        "button_metro_on": "#2F5454",
        "button_text": "#FFFFFF",
        "pulse_color": "#2F5454",
        "pulse_color_hover": "#396262",
    },

    "Twilight Teal": {  # SIN CAMBIOS
        "bg_main": "#1A3042",
        "bg_secondary": "#114047",
        "bg_card": "#1E2A41",
        "text_primary": "#EDEDED",
        "text_secondary": "#B0B0B0",
        "accent": "#095B53",
        "accent_hover": "#114047",
        "select_bg": "#095B53",
        "select_fg": "#EDEDED",
        "button_scan": "#2C2543",
        "button_scan_hover": "#362647",
        "button_play": "#21243F",
        "button_play_hover": "#1E2A41",
        "button_stop": "#50233E",
        "button_stop_hover": "#551E2D",
        "button_nav": "#4B284F",
        "button_nav_hover": "#50233E",
        "button_metro": "#362647",
        "button_metro_hover": "#2C2543",
        "button_metro_on": "#095B53",
        "button_text": "#FFFFFF",
        "pulse_color": "#095B53",
        "pulse_color_hover": "#114047",
    },

    "Deep Space": {
        "bg_main": "#181A1D",
        "bg_secondary": "#101214",
        "bg_card": "#1C1F26",
        "text_primary": "#EDEDED",
        "text_secondary": "#A8A8A8",
        "accent": "#3B91F4",
        "accent_hover": "#2A88F3",
        "select_bg": "#0974F1",
        "select_fg": "#FFFFFF",
        "button_scan": "#5CA5F6",
        "button_scan_hover": "#4C9BF5",
        "button_play": "#1A7EF2",
        "button_play_hover": "#0974F1",
        "button_stop": "#9FCCFA",
        "button_stop_hover": "#8EC2F9",
        "button_nav": "#3B91F4",
        "button_nav_hover": "#2A88F3",
        "button_metro": "#7EB8F8",
        "button_metro_hover": "#6DAFF7",
        "button_metro_on": "#1A7EF2",
        "button_text": "#FFFFFF",
        "pulse_color": "#1A7EF2",
        "pulse_color_hover": "#0974F1",
    },

    "Red Awakening": {
        "bg_main": "#140202",          # rojo oscuro, casi negro
        "bg_secondary": "#200404",     # tono vino muy profundo
        "bg_card": "#2C0807",          # carta ligeramente más cálida
        "text_primary": "#F5E9E7",     # texto principal claro con matiz rosado suave
        "text_secondary": "#CBB3B0",   # texto secundario cálido y legible
        "accent": "#B33939",           # rojo principal, equilibrado entre energía y profundidad
        "accent_hover": "#992F2F",     # rojo más oscuro para hover
        "select_bg": "#732626",        # selección cálida, visible sobre fondo oscuro
        "select_fg": "#FFFFFF",
        "button_scan": "#662222",
        "button_scan_hover": "#5A1E1E",
        "button_play": "#B33939",      # botón principal rojo fuerte
        "button_play_hover": "#992F2F",
        "button_stop": "#661C1C",      # rojo vino oscuro
        "button_stop_hover": "#5A1616",
        "button_nav": "#8C2E2E",
        "button_nav_hover": "#732626",
        "button_metro": "#992F2F",
        "button_metro_hover": "#8C2E2E",
        "button_metro_on": "#B33939",
        "button_text": "#FFFFFF",
        "pulse_color": "#B33939",
        "pulse_color_hover": "#992F2F",
    },
}
